### ISSUE TITLE
Import statement with and without extension

### ISSUE THREAD

**Issue by RobinDeBaets** [RobinDeBaets/componentsjs-generator#7]
Apparently it is possible to specify a filename with or without an extension when importing local files.
For example, `require("../lib/Core")` and `require("../lib/Core.js")` do the same thing.
We need to investigate how this works out in our code and whether this applies to `require` statements as well.

**Comment by RobinDeBaets** [comment]
This is not possible in Typescript, see TS2691

**Comment by adlerfaulkner** [comment]
This is required when creating ECMAScript modules.
eg `import { HttpHandler } from './HttpHandler.js';` instead of `import { HttpHandler } from './HttpHandler';`

When generating components I'm getting this error:
```
ENOENT: no such file or directory, open '/...mydirectorypath.../dist/http/handler/HttpHandler.js.d.ts'
```
